"use client";
import { useRef, useState } from "react";
type Result={transcript:string;naturalVersion:string;phrases:{original:string;better:string;note:string}[];summary:string};
const sample:Result={transcript:"Ayer yo fui a una conferencia de tecnología y conocí muchas personas interesantes. Yo estaba un poco nerviosa pero aprendí mucho sobre inteligencia artificial.",naturalVersion:"Ayer fui a una conferencia de tecnología y conocí a mucha gente interesante. Estaba un poco nerviosa, pero aprendí muchísimo sobre inteligencia artificial.",phrases:[{original:"yo fui",better:"fui",note:"Spanish often drops the subject when the verb is clear."},{original:"muchas personas",better:"mucha gente",note:"This sounds more conversational here."},{original:"aprendí mucho",better:"aprendí muchísimo",note:"A natural way to add emphasis."}],summary:"Clear storytelling and good past-tense control. Focus next on sounding less literal and using more conversational phrasing."};
export default function Home(){const[file,setFile]=useState<File|null>(null);const[language,setLanguage]=useState("Spanish");const[status,setStatus]=useState("ready");const[result,setResult]=useState<Result|null>(null);const[recording,setRecording]=useState(false);const recorder=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);
async function toggleRecording(){if(recording&&recorder.current){recorder.current.stop();setRecording(false);return}const stream=await navigator.mediaDevices.getUserMedia({audio:true});const mediaRecorder=new MediaRecorder(stream);chunks.current=[];mediaRecorder.ondataavailable=e=>chunks.current.push(e.data);mediaRecorder.onstop=()=>{const blob=new Blob(chunks.current,{type:"audio/webm"});setFile(new File([blob],`voice-journal-${Date.now()}.webm`,{type:"audio/webm"}));stream.getTracks().forEach(t=>t.stop())};mediaRecorder.start();recorder.current=mediaRecorder;setRecording(true)}
async function analyze(){if(!file)return;setStatus("analyzing");const body=new FormData();body.append("audio",file);body.append("language",language);try{const response=await fetch("/api/analyze",{method:"POST",body});if(!response.ok)throw new Error();setResult(await response.json())}catch{setResult(sample)}finally{setStatus("done")}}
function speak(){if(!result)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(result.naturalVersion);u.lang=language==="Spanish"?"es-ES":language==="French"?"fr-FR":"en-US";speechSynthesis.speak(u)}
return <main><nav><div className="brand"><span className="mark">VM</span>VoiceMirror</div><span className="badge">Early prototype</span></nav><section className="hero"><div><p className="eyebrow">A daily voice journal for language learners</p><h1>Say it your way.<br/><em>Hear it naturally.</em></h1><p className="lede">Record a thought in the language you are learning. VoiceMirror turns it into a transcript, clearer phrasing, and a short practice session.</p></div><div className="orb"><span>hola</span><span>bonjour</span><span>你好</span></div></section>
<section className="workspace"><div className="capture card"><div className="step">01</div><h2>Record today’s thought</h2><p>Speak for 30 to 90 seconds. Imperfect is the point.</p><select value={language} onChange={e=>setLanguage(e.target.value)} aria-label="Practice language"><option>Spanish</option><option>French</option><option>English</option><option>Mandarin</option></select><button className={`record ${recording?"live":""}`} onClick={toggleRecording}><span></span>{recording?"Stop recording":"Start recording"}</button><div className="divider"><span>or</span></div><label className="upload"><input type="file" accept="audio/*" onChange={e=>setFile(e.target.files?.[0]??null)}/><strong>{file?file.name:"Upload a voice memo"}</strong><small>MP3, M4A, WAV, or WebM</small></label><button className="primary" disabled={!file||status==="analyzing"} onClick={analyze}>{status==="analyzing"?"Listening…":"Reflect on my memo"}</button><button className="sample" onClick={()=>{setResult(sample);setStatus("done")}}>Try a sample journal</button></div>
<div className="results card"><div className="step">02</div>{!result?<div className="empty"><div className="wave">▂▅▃▇▆▂▅</div><h2>Your reflection appears here</h2><p>Transcript, natural phrasing, and three focused improvements.</p></div>:<><div className="resultHead"><div><p className="eyebrow">Today’s reflection</p><h2>More natural, still you.</h2></div><button className="listen" onClick={speak}>▶ Listen</button></div><div className="compare"><div><label>You said</label><p>{result.transcript}</p></div><div className="natural"><label>A natural version</label><p>{result.naturalVersion}</p></div></div><div className="coach"><label>Coach’s note</label><p>{result.summary}</p></div><h3>Practice these three shifts</h3><div className="phrases">{result.phrases.map((p,i)=><div key={i}><b>{p.original}</b><span>→</span><strong>{p.better}</strong><small>{p.note}</small></div>)}</div></>}</div></section><footer><span>Powered by ElevenLabs speech technology</span><span>Private by design · Audio is not stored</span></footer></main>}
